//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErrorLog.Models
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorLogModel", Namespace = "http://schemas.datacontract.org/2004/07/ErrorLog.Models")]
    public partial class ErrorLogModel : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ClassNameField;

        private System.DateTime CreatedOnField;

        private long CreatedOnUnixTimestampField;

        private string ExceptionDataField;

        private string IdField;

        private System.Nullable<System.DateTime> LogTimeField;

        private System.Nullable<long> LogTimeUnixTimestampField;

        private string MessageField;

        private string MethodNameField;

        private string RequestAddresField;

        private string ResponseAddressField;

        private string ResponseMachineNameField;

        private string StackTraceField;

        private string UserIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName
        {
            get
            {
                return this.ClassNameField;
            }
            set
            {
                this.ClassNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn
        {
            get
            {
                return this.CreatedOnField;
            }
            set
            {
                this.CreatedOnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreatedOnUnixTimestamp
        {
            get
            {
                return this.CreatedOnUnixTimestampField;
            }
            set
            {
                this.CreatedOnUnixTimestampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionData
        {
            get
            {
                return this.ExceptionDataField;
            }
            set
            {
                this.ExceptionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LogTime
        {
            get
            {
                return this.LogTimeField;
            }
            set
            {
                this.LogTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> LogTimeUnixTimestamp
        {
            get
            {
                return this.LogTimeUnixTimestampField;
            }
            set
            {
                this.LogTimeUnixTimestampField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestAddres
        {
            get
            {
                return this.RequestAddresField;
            }
            set
            {
                this.RequestAddresField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseAddress
        {
            get
            {
                return this.ResponseAddressField;
            }
            set
            {
                this.ResponseAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseMachineName
        {
            get
            {
                return this.ResponseMachineNameField;
            }
            set
            {
                this.ResponseMachineNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://127.0.0.1:8081/ErrorLogService", ConfigurationName = "IErrorLogService")]
public interface IErrorLogService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Save", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/SaveResponse")]
    string Save(ErrorLog.Models.ErrorLogModel errorLog);

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Save", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/SaveResponse")]
    System.Threading.Tasks.Task<string> SaveAsync(ErrorLog.Models.ErrorLogModel errorLog);

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Get", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/GetResponse")]
    ErrorLog.Models.ErrorLogModel Get(string oid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Get", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/GetResponse")]
    System.Threading.Tasks.Task<ErrorLog.Models.ErrorLogModel> GetAsync(string oid);

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Search", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/SearchResponse")]
    ErrorLog.Models.ErrorLogModel[] Search(System.Nullable<long> startTimestamp, System.Nullable<long> endTimestamp);

    [System.ServiceModel.OperationContractAttribute(Action = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/Search", ReplyAction = "http://127.0.0.1:8081/ErrorLogService/IErrorLogService/SearchResponse")]
    System.Threading.Tasks.Task<ErrorLog.Models.ErrorLogModel[]> SearchAsync(System.Nullable<long> startTimestamp, System.Nullable<long> endTimestamp);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IErrorLogServiceChannel : IErrorLogService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ErrorLogServiceClient : System.ServiceModel.ClientBase<IErrorLogService>, IErrorLogService
{

    public ErrorLogServiceClient()
    {
    }

    public ErrorLogServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public ErrorLogServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ErrorLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public ErrorLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string Save(ErrorLog.Models.ErrorLogModel errorLog)
    {
        return base.Channel.Save(errorLog);
    }

    public System.Threading.Tasks.Task<string> SaveAsync(ErrorLog.Models.ErrorLogModel errorLog)
    {
        return base.Channel.SaveAsync(errorLog);
    }

    public ErrorLog.Models.ErrorLogModel Get(string oid)
    {
        return base.Channel.Get(oid);
    }

    public System.Threading.Tasks.Task<ErrorLog.Models.ErrorLogModel> GetAsync(string oid)
    {
        return base.Channel.GetAsync(oid);
    }

    public ErrorLog.Models.ErrorLogModel[] Search(System.Nullable<long> startTimestamp, System.Nullable<long> endTimestamp)
    {
        return base.Channel.Search(startTimestamp, endTimestamp);
    }

    public System.Threading.Tasks.Task<ErrorLog.Models.ErrorLogModel[]> SearchAsync(System.Nullable<long> startTimestamp, System.Nullable<long> endTimestamp)
    {
        return base.Channel.SearchAsync(startTimestamp, endTimestamp);
    }
}
